name: SimpleHome
version: '1.0.3'
main: com.jellypudding.simpleHome.SimpleHome
api-version: '1.21'
description: "Simple home teleportation plugin with multiple homes support."
author: AlphaAlex115
website: www.minecraftoffline.net
commands:
  sethome:
    description: "Set a named home location (or default 'home')."
    usage: "/sethome [name]"
    permission: simplehome.use
    permission-message: "You don't have permission to set a home."
  home:
    description: "Teleport to a named home location (or default 'home')."
    usage: "/home [name]"
    permission: simplehome.use
    permission-message: "You don't have permission to teleport home."
  delhome:
    description: "Delete a named home location."
    usage: "/delhome <name>"
    permission: simplehome.use
    permission-message: "You don't have permission to delete a home."
  homes:
    description: "List your saved homes."
    usage: "/homes"
    permission: simplehome.use
    permission-message: "You don't have permission to list homes."
permissions:
  simplehome.use:
    description: Allows using basic home commands (/sethome, /home, /delhome, /homes)
    default: true